services:
  db:
    image: postgres:15
    container_name: nest-db
    restart: always
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - nest_db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'
    depends_on:
      - db

volumes:
  nest_db_data:
